"""Initial migration with users, reports and classifications tables

Revision ID: 59ce49cf6d48
Revises: 
Create Date: 2025-11-01 16:30:06.588080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ce49cf6d48'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=False),
    sa.Column('whatsapp_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp_id'),
    sa.UniqueConstraint('whatsapp_number')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Enum('lixo_domestico', 'entulho', 'escoamento_irregular', 'lixo_em_agua', 'esgoto_a_ceu_aberto', 'poluicao_visual', 'outro', name='category'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'resolved', name='reportstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=True),
    sa.Column('problema_identificado', sa.Boolean(), nullable=True),
    sa.Column('category', sa.Enum('lixo_domestico', 'entulho', 'escoamento_irregular', 'lixo_em_agua', 'esgoto_a_ceu_aberto', 'poluicao_visual', 'outro', name='category'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('ai_model', sa.String(length=50), nullable=True),
    sa.Column('local_aparente', sa.Text(), nullable=True),
    sa.Column('tipo_despejo', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('gravidade', sa.Enum('baixa', 'media', 'alta', name='gravidade'), nullable=True),
    sa.Column('risco_saude', sa.Boolean(), nullable=True),
    sa.Column('impacto_meio_ambiente', sa.Text(), nullable=True),
    sa.Column('populacao_prejudicada', sa.Text(), nullable=True),
    sa.Column('descricao_resumida', sa.String(length=300), nullable=True),
    sa.Column('acoes_recomendadas', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classifications')
    op.drop_table('reports')
    op.drop_table('users')
    # ### end Alembic commands ###
