"""create_solicitacoes_coleta_and_ordens_servico

Revision ID: 5abaae149657
Revises: 59ce49cf6d48
Create Date: 2025-11-01 21:31:22.392468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5abaae149657'
down_revision: Union[str, None] = '59ce49cf6d48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacoes_coleta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_solicitante', sa.String(length=255), nullable=False),
    sa.Column('tipo_pessoa', sa.Enum('PF', 'PJ', name='tipopessoa'), nullable=False),
    sa.Column('documento', sa.String(length=18), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('whatsapp', sa.String(length=20), nullable=False),
    sa.Column('quantidade_itens', sa.Integer(), nullable=False),
    sa.Column('endereco', sa.String(length=500), nullable=False),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitacoes_coleta_id'), 'solicitacoes_coleta', ['id'], unique=False)
    op.create_table('ordens_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitacao_id', sa.Integer(), nullable=False),
    sa.Column('numero_os', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA', name='statusos'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes_coleta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solicitacao_id')
    )
    op.create_index(op.f('ix_ordens_servico_id'), 'ordens_servico', ['id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_numero_os'), 'ordens_servico', ['numero_os'], unique=True)
    # Remove tabelas antigas na ordem correta (respeitando foreign keys)
    op.drop_table('classifications')
    op.drop_table('reports')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('report_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('problema_identificado', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('category', postgresql.ENUM('lixo_domestico', 'entulho', 'escoamento_irregular', 'lixo_em_agua', 'esgoto_a_ceu_aberto', 'poluicao_visual', 'outro', name='category'), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ai_model', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('local_aparente', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tipo_despejo', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('gravidade', postgresql.ENUM('baixa', 'media', 'alta', name='gravidade'), autoincrement=False, nullable=True),
    sa.Column('risco_saude', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('impacto_meio_ambiente', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('populacao_prejudicada', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descricao_resumida', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('acoes_recomendadas', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name='classifications_report_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='classifications_pkey'),
    sa.UniqueConstraint('report_id', name='classifications_report_id_key')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('whatsapp_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('whatsapp_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('whatsapp_id', name='users_whatsapp_id_key'),
    sa.UniqueConstraint('whatsapp_number', name='users_whatsapp_number_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('category', postgresql.ENUM('lixo_domestico', 'entulho', 'escoamento_irregular', 'lixo_em_agua', 'esgoto_a_ceu_aberto', 'poluicao_visual', 'outro', name='category'), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'resolved', name='reportstatus'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='reports_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reports_pkey')
    )
    op.drop_index(op.f('ix_ordens_servico_numero_os'), table_name='ordens_servico')
    op.drop_index(op.f('ix_ordens_servico_id'), table_name='ordens_servico')
    op.drop_table('ordens_servico')
    op.drop_index(op.f('ix_solicitacoes_coleta_id'), table_name='solicitacoes_coleta')
    op.drop_table('solicitacoes_coleta')
    # ### end Alembic commands ###
