"""add_catadores

Revision ID: dfdae5b48dea
Revises: d1fe4896552c
Create Date: 2025-11-01 23:07:20.536371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfdae5b48dea'
down_revision: Union[str, None] = 'd1fe4896552c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='statuscatador'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_catadores_id'), 'catadores', ['id'], unique=False)
    op.create_table('catadores_empresas',
    sa.Column('catador_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('data_vinculo', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catador_id'], ['catadores.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('catador_id', 'empresa_id')
    )
    op.drop_index('ix_empresas_cnpj', table_name='empresas')
    op.create_unique_constraint(
        'empresas_cnpj_key', 'empresas', ['cnpj']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'empresas_cnpj_key', 'empresas', type_='unique'
    )
    op.create_index('ix_empresas_cnpj', 'empresas', ['cnpj'], unique=True)
    op.drop_table('catadores_empresas')
    op.drop_index(op.f('ix_catadores_id'), table_name='catadores')
    op.drop_table('catadores')
    # ### end Alembic commands ###
